### ISSUE TITLE
Suggestion to Enhance Inserted Value Format

### ISSUE THREAD

**Issue by yakovlev-i-a** [hedgehog1833/obsidian-timetracker#107]
Hello,

Thank you for your excellent work! The plugin works perfectly, and I truly appreciate it.

I’ve found the countdown time insertion feature to be very useful and had an idea for improving it further.

Like many users, I rely on the Dataview plugin to organize and collect data from my daily notes. It’s important for me to track the time spent on specific tasks in my list. To achieve this, I currently use an inline function in the format [t::1h17m], for example. However, at the moment, I have to stop the time tracker and manually convert the tracked time from the plugin window into the required format for my task list.

It would be incredibly convenient if the plugin allowed users to set a custom format (with special characters) for the time when inserting it via a hotkey. For instance, a format like `["timespent::"h"hours"m"minutes"]`
 or something similar would be ideal. With such a feature, it would be possible to directly insert the tracked time as an inline parameter for Dataview without additional manual steps.

I’ve attached some screenshots for reference.

![image](https://github.com/user-attachments/assets/9677a25c-a8e5-42b3-a883-26dff54353d0)
![image](https://github.com/user-attachments/assets/8e43aae9-5cb1-482a-9ff6-a61502651ad3)

Thank you again for your work, and I look forward to hearing your thoughts on this suggestion!

All the best,
Igor

**Comment by hedgehog1833** [comment]
Hi Igor,
thank you for using the plugin and providing this feature request! I'm very happy to hear that you like it.

Sounds like a reasonable approach to me, I'll try to have a deeper look into it over the holidays and will get back to you here!

Best regards
Nils

**Comment by Pythoon3** [comment]
Hello,
Joining the author of the post. The implementation of this function will simplify the procedure for keeping daily notes!

Best regards,
Anastasia

**Comment by hedgehog1833** [comment]
Hi @yakovlev-i-a and @Pythoon3,
I just released [1.5.0](https://github.com/hedgehog1833/obsidian-timetracker/releases/tag/1.5.0) with a simple formatting solution. I'll close this issue, please reopen if you still need something. Implemented in https://github.com/hedgehog1833/obsidian-timetracker/commit/045ec8f8a1ec9505859893bd69ae3641a2381ba8
Best regards
Nils

**Comment by yakovlev-i-a** [comment]
Hi!

Thank you so much for this enhancement—it works perfectly! I'm really enjoying this plugin even more now. Your work is greatly appreciated!

Best regards,
Igor
