### ISSUE TITLE
Set Timer

### ISSUE THREAD

**Issue by kaputr** [hedgehog1833/obsidian-timetracker#25]
Hi there,

I'm very satisfied with how this works atm, but consider the stupidity of the user: when I watch a film, sometimes I forget to hit the timetracker startbutton, and 15 Minutes in I notice that I have to take notes. So I have to pause the video, start the timer, go to the kitchen and cook some tea, until it is in sync.

Maybe add a function to edit the value of the timer, so you don't always have to start at zero.

btw I love the plugin.

All the best,
kaputr

**Comment by hedgehog1833** [comment]
Sounds reasonable. I'll have a look at that as soon as time permits ☺️

**Comment by kaputr** [comment]
thanks buddy, I appreciate it.
I can send you a coffee if it makes you work faster

**Comment by hedgehog1833** [comment]
I just released version [1.2.0](https://github.com/hedgehog1833/obsidian-timetracker/releases/tag/1.2.0) which includes a button to set the timer value.
